# Generated by Django 2.2.2 on 2019-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicationform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('bday', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('cate', models.CharField(default='', max_length=8, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fname', models.CharField(default='', max_length=20, null=True)),
                ('foccu', models.CharField(default='', max_length=20, null=True)),
                ('desig', models.CharField(default='', max_length=20, null=True)),
                ('cpf', models.IntegerField(null=True)),
                ('section', models.CharField(default='', max_length=15, null=True)),
                ('city', models.CharField(default='', max_length=25, null=True)),
                ('phno', models.IntegerField(null=True)),
                ('mono', models.IntegerField(null=True)),
                ('insname', models.CharField(default='', max_length=30, null=True)),
                ('brname', models.CharField(default='', max_length=30, null=True)),
                ('sem', models.IntegerField(null=True)),
                ('semmarks', models.IntegerField(null=True)),
                ('twelv', models.IntegerField(null=True)),
                ('menname', models.CharField(max_length=20, null=True)),
                ('des1', models.CharField(max_length=20, null=True)),
                ('site', models.CharField(max_length=20, null=True)),
                ('loc', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
